const BASE_URL = process.env.NEXT_PUBLIC_API_URL as string;
const API_LOGIN_PEMBELI = process.env.BACKEND_API_PEMBELI;
const API_LOGIN_PENITIP = process.env.BACKEND_API_PENITIP;
const API_LOGIN_PEGAWAI = process.env.BACKEND_API_PEGAWAI;
const API_LOGIN_ORGANISASI = process.env.BACKEND_API_ORGANISASI;
const JWT_SECRET = process.env.JWT_SECRET as string;

export {
  BASE_URL,
  API_LOGIN_ORGANISASI,
  API_LOGIN_PEGAWAI,
  API_LOGIN_PEMBELI,
  API_LOGIN_PENITIP,
  JWT_SECRET,
};
